name: nitelyfe
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  
  cupertino_icons: ^1.0.0
  curved_navigation_bar: ^0.3.7
  
  firebase_core: ^0.5.3
  firebase_analytics: ^6.3.0
  firebase_auth: ^0.18.4+1
  cloud_firestore: ^0.14.4

  geolocator: ^6.1.13
  location: ^3.2.1
  geocoder: ^0.2.1
  geoflutterfire: ^2.2.1
  google_maps_flutter: ^1.1.1
  flutter_spinkit: ^4.1.2+1

  shared_preferences: ^0.5.8
  rxdart: ^0.24.1


dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:

  uses-material-design: true

  assets:
    - images/

  fonts:
    - family: Comfortaa
      fonts:
        - asset: fonts/Comfortaa-Regular.ttf
